import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Is_browser_supported_wrapper from "./wrappers/Is_browser_supported_wrapper/Is_browser_supported_wrapper";
import Is_user_logged_in from "./wrappers/Is_user_logged_in/Is_user_logged_in";
import { app_title } from "./app_conf";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: app_title,
  description: "Generated by create next app",
  icons: {
    icon: "/fsque/assets/favicon.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Is_browser_supported_wrapper>
          <Is_user_logged_in>
            {children}
          </Is_user_logged_in>
        </Is_browser_supported_wrapper>
      </body>
    </html>
  );
}
